---
inherit_from: .rubocop_todo.yml

Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Layout/DotPosition:
  EnforcedStyle: trailing

Metrics/BlockLength:
  Exclude:
    - spec/**/*_spec.rb
    - spec/support/shared_examples/**/*.rb

Metrics/LineLength:
  Max: 120

Naming/FileName:
  Exclude:
    - lib/ffi-gdal.rb
    - spec/ffi-gdal_spec.rb

Naming/UncommunicativeMethodParamName:
  AllowedNames: [x, y, z]

Style/Documentation:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/FormatString:
  EnforcedStyle: percent

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%i': '[]'
    '%w': '[]'
    '%W': '[]'

Style/SymbolArray:
  Enabled: true

AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  Exclude:
    - vendor/bundle/**/*
  TargetRubyVersion: 2.6
