Metrics/ClassLength:
  Max: 300

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 20

Metrics/ParameterLists:
  Exclude:
    - lib/gdal/driver.rb

Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Style/Documentation:
  Enabled: false

Style/DotPosition:
  EnforcedStyle: trailing

Style/FormatString:
  EnforcedStyle: percent

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%i': '[]'
    '%w': '[]'
    '%W': '[]'

Style/SymbolArray:
  Enabled: true

AllCops:
  Include:
    - Gemfile
    - ffi-gdal.gemspec
  Exclude:
    - vendor/bundle/**/*
