# You can use a Docker image from Docker Hub or your own container
# registry for your build environment.
image: agrian/ubuntugis-ruby:latest

pipelines:
  default:
    - step:
        script: # Modify the commands below to build your repository.
          - ruby --version
          - gem install bundler
          - gem sources -a http://$AGRIAN_GEMS_USERNAME:$AGRIAN_GEMS_PASSWORD@gems.agrian.com/
          - bundle config gems.agrian.com $AGRIAN_GEMS_USERNAME:$AGRIAN_GEMS_PASSWORD
          - bundler --version
          - bundle install
          - bundle exec rake spec
          # - bundle exec rubocop
